merchex/merchex/urls.py
from django.contrib import admin
from django.urls import path
from listings import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('bands/', views.band_list, name='band-list'),
    path('bands/<int:id>/', views.band_details, name='band-detail'),
    path('bands/create/', views.band_create, name='band-create'),    
    path('bands/<int:id>/change/', views.band_update, name='band-update'),
    path('bands/<int:id>/delete/', views.band_delete, name='band-delete'),
    path('about-us/', views.about, name='about'),
    path('sample/', views.sample, name='sample'),
    path('contact-us/', views.contact, name='contact'),
    path('listings/', views.listing_list, name='listing-list'),
    path('listings/<int:id>/', views.listing_details, name='listing-detail'),
    path('listings/create/', views.listing_create, name='listing-create'),
    path('listings/<int:id>/update/', views.listing_update, name='listing-update'),
    path('listings/<int:id>/delete/', views.listing_delete, name='listing-delete'),
    path('email-sent/', views.email_sent, name='email-sent'),
]

merchex/listings/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator

class Band(models.Model):
    class Genre(models.TextChoices):
        HIP_HOP = 'HH'
        SYNTH_POP = 'SP'
        ALTERNATIVE_ROCK = 'AR'

    name = models.fields.CharField(max_length=100)
    genre = models.fields.CharField(choices=Genre.choices, max_length=5)
    biography = models.fields.CharField(max_length=1000)
    year_formed = models.fields.IntegerField(
        validators=[MinValueValidator(1900), MaxValueValidator(2021)]
    )
    active = models.fields.BooleanField(default=True)
    official_homepage = models.fields.URLField(null=True, blank=True)

    def __str__(self):
        return f'{self.name}'
    
class Listing(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=1000, blank=True, default='')
    sold = models.BooleanField(default=False)
    year = models.IntegerField(null=True, blank=True)
    TYPE_CHOICES = [
        ('RE', 'Records'),
        ('CL', 'Clothing'),
        ('PO', 'Posters'),
        ('MI', 'Miscellaneous'),
    ]
    type = models.CharField(max_length=2, choices=TYPE_CHOICES, default='MI') 
    band = models.ForeignKey(Band, null=True, on_delete=models.SET_NULL)

merchex/listings/forms.py
from django import forms
from listings.models import Band, Listing

class ContactUsForm(forms.Form):
    name = forms.CharField(required=False)
    email = forms.EmailField()
    message = forms.CharField(max_length=1000)

class BandForm(forms.ModelForm):
    class Meta:
        model = Band
        exclude = ('active', 'official_homepage')

class ListingForm(forms.ModelForm):
    class Meta:
        model = Listing
        fields = '__all__'

merchex/listings/views.py
from django.shortcuts import render
from listings.models import Band, Listing
from listings.forms import BandForm, ContactUsForm, ListingForm
from django.core.mail import send_mail
from django.shortcuts import redirect

def band_list(request):
    bands = Band.objects.all()
    return render(request, 
                  'listings/band_list.html',
                  {'bands': bands})

def band_details(request, id):
    band = Band.objects.get(id=id)
    return render(request,
                  'listings/band_details.html',
                  {'band': band})

def band_create(request):
    if request.method == 'POST':
        form = BandForm(request.POST)
        if form.is_valid():
            band = form.save()
            return redirect('band-detail', band.id)
    else:
        form = BandForm()
    return render(request,
                'listings/band_create.html',
                {'form': form})
    
def band_update(request, id):
    band = Band.objects.get(id=id)
    if request.method == 'POST':
        form = BandForm(request.POST, instance=band)
        if form.is_valid():
            form.save()
            return redirect('band-detail', band.id)
    else:
        form = BandForm(instance=band)
    return render(request,
                'listings/band_update.html',
                {'form': form})

def band_delete(request, id):
    band = Band.objects.get(id=id)
    if request.method == 'POST':
        band.delete()
        return redirect('band_list')
    return render(request,
                    'listings/band_delete.html',
                    {'band': band})

def about(request):
    return render(request, 'listings/about.html')

def contact(request):
    if request.method == 'POST':
        form = ContactUsForm(request.POST)
        if form.is_valid():
            send_mail(
                subject=f'Message from {form.cleaned_data["name"] or "anonymous"} via MerchEx Contact Us form',
                message=form.cleaned_data['message'],
                from_email=form.cleaned_data['email'],
                recipient_list=['admin@merchex.xyz'],
            )
            return redirect('email-sent')
    else:
        form = ContactUsForm()
    return render(request,
                'listings/contact.html',
                {'form': form})

def listing_list(request):
    listings = Listing.objects.all()
    return render(request, 'listings/listing_list.html', {'listings': listings})

def listing_details(request, id):
    listing = Listing.objects.get(id=id)
    return render(request, 'listings/listing_details.html', {'listing': listing})

def listing_create(request):
    if request.method == 'POST':
        form = ListingForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('listing-list')
    else:
        form = ListingForm()
    return render(request, 
                  'listings/listing_create.html', 
                  {'form': form})

def listing_update(request, id):
    listing = Listing.objects.get(id=id)
    if request.method == 'POST':
        form = ListingForm(request.POST, instance=listing)
        if form.is_valid():
            form.save()
            return redirect('listing-detail', id=listing.id)
    else:
        form = ListingForm(instance=listing)
    return render(request, 'listings/listing_update.html', {'form': form, 'listing': listing})

def listing_delete(request, id):
    listing = Listing.objects.get(id=id)
    if request.method == 'POST':
        listing.delete()
        return redirect('listing-list')
    return render(request, 'listings/listing_delete.html', {'listing': listing})

def sample(request):
    return render(request, 'listings/sample.html')

def email_sent(request):
    return render(request, 'listings/email_sent.html')

merchex/listings/templates/listings/about.html
{% extends 'listings/base.html' %}

{% block content %}

    <h1>About Us</h1>
    <p>Welcome to the About page.</p>

{% endblock %}

merchex/listings/templates/listings/band_create.html
{% extends 'listings/base.html' %}

{% block content %}

    <h1>Create new Band</h1>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit">
    </form>

{% endblock %}

merchex/listings/templates/listings/band_delete.html
{% extends 'listings/base.html' %}
{% block content %}
    <h1>Delete Band</h1>
    <p>Are you sure you want to delete this band?: {{ band.name }}</p>
    <form action="" method="post">
        {% csrf_token %}
        <input type="submit" value="Delete">
    </form>
{% endblock %}

merchex/listings/templates/listings/band_details.html
{% extends 'listings/base.html' %}
{% block content %}

    <h2>{{ band.name }}</h2>

    <ul>
        <li>Genre: {{ band.get_genre_display }}</li>
        <li>Year formed: {{ band.year_formed }}</li>
        <li>Active: {{ band.active|yesno }}</li>
        {% if band.official_homepage %}
            <li><a href="{{ band.official_homepage }}">{{ band.official_homepage }}</a></li>
        {% endif %}
    </ul>

    <p>{{ band.biography }}</p>
    <a href="{% url 'band-update' band.id %}">Edit this Band</a>
    <a href="{% url 'band-delete' band.id %}">Delete Band</a>
    <a href="{% url 'band-list' %}">Back to all Bands</a>
{% endblock %}

merchex/listings/templates/listings/band_list.html
{% extends 'listings/base.html' %}
{% block content %}

<h1>Bands</h1>
<a href="{% url 'band-create' %}">Create new Band</a>
<ul>
    {% for band in bands %}
      <li>
        <a href="{% url 'band-detail' band.id %}">{{ band.name }}</a>
        - <a href="{% url 'band-update' band.id %}">[Edit]</a>
        - <a href="{% url 'band-delete' band.id %}">[Delete]</a>
      </li>
    {% endfor %}
  </ul>

{% endblock %}

merchex/listings/templates/listings/band_update.html
{% extends 'listings/base.html' %}
{% block content %}
    <h1>Update Band: {{ band.name }}</h1>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit">
    </form>
{% endblock %}

merchex/listings/templates/listings/base.html
{% load static %}
<html>
    <head><title>Merchex</title></head>
    <link rel="stylesheet" href="{% static 'listings/styles.css' %}" />
    <body>
        <nav>
            <a href="{% url 'band-list' %}">Bands</a>
            <a href="{% url 'listing-list' %}">Listings</a>
            <a href="{% url 'about' %}">About Us</a>
            <a href="{% url 'contact' %}">Contact Us</a>
            <a href="{% url 'sample' %}">Sample</a>
        </nav>

        {% block content %}
        {% endblock %}

    </body>
</html>

merchex/listings/templates/listings/email_sent.html
{% extends 'listings/base.html' %}

{% block content %}
    <h1>Email Sent</h1>
    <p>Thank you for your message! We will get back to you shortly.</p>
    <a href="{% url 'contact' %}">Go back to Contact Us page</a>
{% endblock %}

merchex/listings/templates/listings/listing_create.html
{% extends 'listings/base.html' %}

{% block content %}
    <h1>Create a New Listing</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Create Listing</button>
    </form>
{% endblock %}

merchex/listings/templates/listings/listing_delete.html
{% extends 'listings/base.html' %}
{% block content %}
    <h1>Delete Listing</h1>
    <p>Are you sure you want to delete this listing?: {{ listing.title }}</p>
    <form action="" method="post">
        {% csrf_token %}
        <input type="submit" value="Delete">
    </form>
{% endblock %}

merchex/listings/templates/listings/listing_list.html
{% extends 'listings/base.html' %}

{% block content %}
    <h1>Listings</h1>
    <a href="{% url 'listing-create' %}">Create New Listing</a>

    <ul>
        {% for listing in listings %}
            <li>
                <a href="{% url 'listing-detail' listing.id %}">{{ listing.title }}</a> 
                - <a href="{% url 'listing-update' listing.id %}">[Edit]</a>
                - <a href="{% url 'listing-update' listing.id %}">[Delete]</a>
            </li>
        {% endfor %}
    </ul>
{% endblock %}

merchex/listings/templates/listings/listing_update.html
{% extends 'listings/base.html' %}
{% block content %}
    <h1>Update Listing: {{ listing.title }}</h1>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit">
    </form>
{% endblock %}

merchex/listings/templates/listings/listings.html
{% extends 'listings/base.html' %}

{% block content %}

    <h1>Listings</h1>
        <ul>
            {% for listing in listings %}
                <li>{{ listing.title }}</li>
            {% empty %}
                <li>No listings available.</li>
            {% endfor %}
        </ul>

{% endblock %}

merchex/listings/templates/listings/sample.html
{% extends 'listings/base.html' %}

{% block content %}

    <h1>Just a Sample page</h1>
    <p>I guess it works..</p>

{% endblock %}